In [20]:
from sys import executable
print(executable)

/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7

In [22]:
# The xls file is encryted so the data preprocessing process has to use xlwings module
import pandas as pd
path = r'/Users/simjaegwang/Desktop/RAM/2019/Real_estate_python/kbdatas.xls'
raw_data = pd.read_excel(path, sheet_name='매매종합')

ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.

In [18]:
import pandas as pd
import xlwings as xw #importing Xlwings module 

path = r'/Users/simjaegwang/Desktop/RAM/2019/Real_estate_python/kbdatas.xls'
wb = xw.Book(path)
sheet = wb.sheets['매매종합']
row_num = 410
data_range = 'A2:GE'+str(row_num)
raw_data = sheet[data_range].options(pd.DataFrame, index=False, header=True).value
print(raw_data)

                 구분       전국       서울              강북         NaN  \
0              None     None     None            None         강북구
1    Classification    Total    Seoul  Northern seoul  Gangbuk-gu
2              86.1  34.6561  30.0438           41.94        None
3                 2  34.6561  30.0438         41.8891        None
4                 3   34.708  30.0024         41.8891        None
..              ...      ...      ...             ...         ...
403               6  99.5385  100.037         100.254     100.865
404               7  99.5314  100.302         100.521     101.004
405               8  99.5861  100.682         101.017      102.99
406               9  99.6396   101.06         101.292     103.051
407              10  99.7334  101.432          101.53     103.091

             NaN       NaN        NaN            NaN      NaN  ...      NaN  \
0            광진구       노원구        도봉구           동대문구      마포구  ...      의창구
1    Gwangjin-gu  Nowon-gu  Dobong-gu  Dongdaemun-gu  Mapo-gu  ...  Uichang
2           None      None       None           None     None  ...     None
3           None      None       None           None     None  ...     None
4           None      None       None           None     None  ...     None
..           ...       ...        ...            ...      ...  ...      ...
403      99.8983   100.095    99.8762        100.352  99.9908  ...  97.6907
404      100.212   100.442    100.074        100.723  100.317  ...   97.092
405      100.668       101    100.224        100.984  100.979  ...   96.993
406      100.877   101.222    100.438        101.329  101.442  ...  96.7089
407      101.267   101.366    100.562        101.627  101.881  ...  96.4059

         NaN       양산     거제       진주       김해         통영       제주도  \
0        진해구     None   None     None     None       None      None
1     Jinhae  Yangsan  Geoje    Jinju   Gimhae  Tongyoung  Jeju-do
2       None     None   None     None     None       None      None
3       None     None   None     None     None       None      None
4       None     None   None     None     None       None      None
..       ...      ...    ...      ...      ...        ...       ...
403  99.0593     None   None  97.9095  96.9309       None      None
404  98.8455     None   None  97.4756   96.055       None      None
405  98.8204     None   None  98.4843  95.6924       None      None
406  98.2978     None   None  98.1888  95.3363       None      None
407   98.046     None   None  97.9575  94.8948       None      None

            제주/\n서귀포                   기타지방
0               None                   None
1    Jeju/\nSeogwipo  Non-Metropolitan Area
2               None                   None
3               None                   None
4               None                   None
..               ...                    ...
403          99.1183                98.5402
404          99.0396                98.2511
405          99.0585                98.0999
406          98.3358                97.9116
407           97.879                97.7453

[408 rows x 187 columns]

In [33]:
path = r'/Users/simjaegwang/Desktop/RAM/2019/Real_estate_python/kbdatas.xls'
wb = xw.Book(path)
sheet = wb.sheets['매매종합']
row_num = 410
data_range = 'A2:GE'+str(row_num)
raw_data = sheet[data_range].options(pd.DataFrame, index=False, header=True).value
big_col = list(raw_data.columns)
small_col = list(raw_data.iloc[0])
#for num,gu_data in enumerate(small_col):
#    if gu_data == None:
#        small_col[num] = big_col[num]
print(big_col)
print('\n')
print(small_col)

['구분', '전국', '서울', '강북', None, None, None, None, None, None, None, None, None, None, None, None, None, None, '강남', None, None, None, None, None, None, None, None, None, None, None, '6개광역시', '부산', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, '대구', None, None, None, None, None, None, None, None, '인천', None, None, None, None, None, None, None, None, '광주', None, None, None, None, None, '대전', None, None, None, None, None, '울산', None, None, None, None, None, '5개광역시\n(인천外)', '수도권', '세종', '경기', '수원', None, None, None, None, '성남', None, None, None, '고양', None, None, None, '안양', None, None, '부천', '의정부', '광명', '평택', '안산', None, None, '과천', '구리', '남양주', '용인', None, None, None, '시흥', '군포', '의왕', '하남', '오산', '파주', '이천', '안성', '김포', '양주', '동두천', '광주', '화성', '강원', '춘천', None, '원주', '충북', '청주', None, None, None, None, '충주', '제천', '충남', '천안', None, None, '공주', '아산', '논산', '계룡', '당진', '서산', '전북', '전주', None, None, '익산', '군산', '전남', '목포', '순천', '광양', '여수', '경북', '포항', None, None, '구미', '경산', '안동', '김천', '경남', '창원', None, None, None, None, None, '양산', '거제', '진주', '김해', '통영', '제주도', '제주/\n서귀포', '기타지방']


[None, None, None, None, '강북구', '광진구', '노원구', '도봉구', '동대문구', '마포구', '서대문구', '성동구', '성북구', '용산구', '은평구', '종로구', '중구', '중랑구', None, '강남구', '강동구', '강서구', '관악구', '구로구', '금천구', '동작구', '서초구', '송파구', '양천구', '영등포구', None, None, '중구', '서구', '동구', '영도구', '부산진구', '동래구', '남구', '북구', '해운대구', '사하구', '금정구', '연제구', '수영구', '사상구', '기장군', '강서구', None, '중구', '동구', '서구', '남구', '북구', '수성구', '달서구', '달성군', None, '중구', '동구', '미추홀구', '연수구', '남동구', '부평구', '계양구', '서구', None, '동구', '서구', '남구', '북구', '광산구', None, '동구', '중구', '서구', '유성구', '대덕구', None, '중구', '남구', '동구', '북구', '울주군', None, None, None, None, None, '장안구', '권선구', '팔달구', '영통구', None, '수정구', '중원구', '분당구', None, '덕양구', '일산동구', '일산서구', None, '만안구', '동안구', None, None, None, None, None, '단원구', '상록구', None, None, None, None, '처인구', '기흥구', '수지구', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, '강릉', None, None, None, '상당구', '서원구', '청원구', '흥덕구', None, None, None, None, '동남구', '서북구', None, None, None, None, None, None, None, None, '완산구', '덕진구', None, None, None, None, None, None, None, None, None, '남구', '북구', None, None, None, None, None, None, '마산합포구', '마산회원구', '성산구', '의창구', '진해구', None, None, None, None, None, None, None, None]

In [49]:
path = r'/Users/simjaegwang/Desktop/RAM/2019/Real_estate_python/kbdatas.xls'
wb = xw.Book(path)
sheet = wb.sheets['매매종합']
row_num = 410
data_range = 'A2:GE'+str(row_num)
raw_data = sheet[data_range].options(pd.DataFrame, index=False, header=True).value

bignames = '서울 대구 부산 대전 광주 인천 울산 세종 경기 강원 충북 충남 전북 전남 경북 경남 제주도 6개광역시 5개광역시 수도권 기타지방 구분 전국'
bignames_list = bignames.split(' ')
big_col = list(raw_data.columns)
small_col = list(raw_data.iloc[0])

for num,gu_data in enumerate(small_col):
    if gu_data == None:
        small_col[num] = big_col[num]
    check = num
    while True:
        if big_col[check] in bignames_list:
            big_col[num] = big_col[check]
            break
        else:
            check = check - 1


big_col[129]= '경기'
big_col[130]= '경기'
big_col[185]= '서귀포'

raw_data.columns = [big_col,small_col]
new_col_data = raw_data.drop([0,1])

print(new_col_data)

       구분       전국       서울                                               \
       구분       전국       서울       강북      강북구      광진구      노원구      도봉구
2    86.1  34.6561  30.0438    41.94     None     None     None     None
3       2  34.6561  30.0438  41.8891     None     None     None     None
4       3   34.708  30.0024  41.8891     None     None     None     None
5       4  34.4486  29.8366  41.7366     None     None     None     None
6       5  34.2929   29.588  41.2791     None     None     None     None
..    ...      ...      ...      ...      ...      ...      ...      ...
403     6  99.5385  100.037  100.254  100.865  99.8983  100.095  99.8762
404     7  99.5314  100.302  100.521  101.004  100.212  100.442  100.074
405     8  99.5861  100.682  101.017   102.99  100.668      101  100.224
406     9  99.6396   101.06  101.292  103.051  100.877  101.222  100.438
407    10  99.7334  101.432   101.53  103.091  101.267  101.366  100.562

                       ...       경남                                         \
        동대문구      마포구  ...      의창구      진해구    양산    거제       진주       김해
2       None     None  ...     None     None  None  None     None     None
3       None     None  ...     None     None  None  None     None     None
4       None     None  ...     None     None  None  None     None     None
5       None     None  ...     None     None  None  None     None     None
6       None     None  ...     None     None  None  None     None     None
..       ...      ...  ...      ...      ...   ...   ...      ...      ...
403  100.352  99.9908  ...  97.6907  99.0593  None  None  97.9095  96.9309
404  100.723  100.317  ...   97.092  98.8455  None  None  97.4756   96.055
405  100.984  100.979  ...   96.993  98.8204  None  None  98.4843  95.6924
406  101.329  101.442  ...  96.7089  98.2978  None  None  98.1888  95.3363
407  101.627  101.881  ...  96.4059   98.046  None  None  97.9575  94.8948

            제주도      서귀포     기타지방
       통영   제주도 제주/\n서귀포     기타지방
2    None  None     None     None
3    None  None     None     None
4    None  None     None     None
5    None  None     None     None
6    None  None     None     None
..    ...   ...      ...      ...
403  None  None  99.1183  98.5402
404  None  None  99.0396  98.2511
405  None  None  99.0585  98.0999
406  None  None  98.3358  97.9116
407  None  None   97.879  97.7453

[406 rows x 187 columns]

In [56]:
path = r'/Users/simjaegwang/Desktop/RAM/2019/Real_estate_python/kbdatas.xls'
wb = xw.Book(path)
sheet = wb.sheets['매매종합']
row_num = 410
data_range = 'A2:GE'+str(row_num)
raw_data = sheet[data_range].options(pd.DataFrame, index=False, header=True).value

bignames = '서울 대구 부산 대전 광주 인천 울산 세종 경기 강원 충북 충남 전북 전남 경북 경남 제주도 6개광역시 5개광역시 수도권 기타지방 구분 전국'
bignames_list = bignames.split(' ')
big_col = list(raw_data.columns)
small_col = list(raw_data.iloc[0])

for num,gu_data in enumerate(small_col):
    if gu_data == None:
        small_col[num] = big_col[num]
    check = num
    while True:
        if big_col[check] in bignames_list:
            big_col[num] = big_col[check]
            break
        else:
            check = check - 1


big_col[129]= '경기'
big_col[130]= '경기'
big_col[185]= '서귀포'

raw_data.columns = [big_col,small_col]
new_col_data = raw_data.drop([0,1])

index_list = list(new_col_data['구분']['구분'])
new_index =[]

for num, raw_index in enumerate(index_list):
    temp = str(raw_index).split('.')
    if int(temp[0])>12:
        if len(temp[0]) == 2:
            new_index.append('19'+temp[0]+'.'+temp[1])
        else:
            new_index.append(temp[0]+'.'+temp[1])
    else:
        new_index.append(new_index[num-1].split('.')[0]+'.'+temp[0])

new_col_data.set_index(pd.to_datetime(new_index),inplace = True)
cleaned_data = new_col_data.drop(('구분','구분'),axis=1)

print(cleaned_data)

                 전국       서울                                               \
                 전국       서울       강북      강북구      광진구      노원구      도봉구
1986-01-01  34.6561  30.0438    41.94     None     None     None     None
1986-02-01  34.6561  30.0438  41.8891     None     None     None     None
1986-03-01   34.708  30.0024  41.8891     None     None     None     None
1986-04-01  34.4486  29.8366  41.7366     None     None     None     None
1986-05-01  34.2929   29.588  41.2791     None     None     None     None
...             ...      ...      ...      ...      ...      ...      ...
2019-06-01  99.5385  100.037  100.254  100.865  99.8983  100.095  99.8762
2019-07-01  99.5314  100.302  100.521  101.004  100.212  100.442  100.074
2019-08-01  99.5861  100.682  101.017   102.99  100.668      101  100.224
2019-09-01  99.6396   101.06  101.292  103.051  100.877  101.222  100.438
2019-10-01  99.7334  101.432   101.53  103.091  101.267  101.366  100.562

                                       ...       경남                       \
               동대문구      마포구     서대문구  ...      의창구      진해구    양산    거제
1986-01-01     None     None     None  ...     None     None  None  None
1986-02-01     None     None     None  ...     None     None  None  None
1986-03-01     None     None     None  ...     None     None  None  None
1986-04-01     None     None     None  ...     None     None  None  None
1986-05-01     None     None     None  ...     None     None  None  None
...             ...      ...      ...  ...      ...      ...   ...   ...
2019-06-01  100.352  99.9908  101.142  ...  97.6907  99.0593  None  None
2019-07-01  100.723  100.317  101.636  ...   97.092  98.8455  None  None
2019-08-01  100.984  100.979  102.367  ...   96.993  98.8204  None  None
2019-09-01  101.329  101.442  102.674  ...  96.7089  98.2978  None  None
2019-10-01  101.627  101.881  102.845  ...  96.4059   98.046  None  None

                                     제주도      서귀포     기타지방
                 진주       김해    통영   제주도 제주/\n서귀포     기타지방
1986-01-01     None     None  None  None     None     None
1986-02-01     None     None  None  None     None     None
1986-03-01     None     None  None  None     None     None
1986-04-01     None     None  None  None     None     None
1986-05-01     None     None  None  None     None     None
...             ...      ...   ...   ...      ...      ...
2019-06-01  97.9095  96.9309  None  None  99.1183  98.5402
2019-07-01  97.4756   96.055  None  None  99.0396  98.2511
2019-08-01  98.4843  95.6924  None  None  99.0585  98.0999
2019-09-01  98.1888  95.3363  None  None  98.3358  97.9116
2019-10-01  97.9575  94.8948  None  None   97.879  97.7453

[406 rows x 186 columns]

In [65]:
def KBpriceindex_preprocessing(path,data_type):
    wb = xw.Book(path)
    sheet = wb.sheets[data_type]
    row_num = 410
    data_range = 'A2:GE'+str(row_num)
    raw_data = sheet[data_range].options(pd.DataFrame, index=False, header=True).value

    bignames = '서울 대구 부산 대전 광주 인천 울산 세종 경기 강원 충북 충남 전북 전남 경북 경남 제주도 6개광역시 5개광역시 수도권 기타지방 구분 전국'
    bignames_list = bignames.split(' ')
    big_col = list(raw_data.columns)
    small_col = list(raw_data.iloc[0])

    for num,gu_data in enumerate(small_col):
        if gu_data == None:
            small_col[num] = big_col[num]
        check = num
        while True:
            if big_col[check] in bignames_list:
                big_col[num] = big_col[check]
                break
            else:
                check = check - 1


    big_col[129]= '경기'
    big_col[130]= '경기'
    big_col[185]= '서귀포'

    raw_data.columns = [big_col,small_col]
    new_col_data = raw_data.drop([0,1])

    index_list = list(new_col_data['구분']['구분'])
    new_index =[]

    for num, raw_index in enumerate(index_list):
        temp = str(raw_index).split('.')
        if int(temp[0])>12:
            if len(temp[0]) == 2:
                new_index.append('19'+temp[0]+'.'+temp[1])
            else:
                new_index.append(temp[0]+'.'+temp[1])
        else:
            new_index.append(new_index[num-1].split('.')[0]+'.'+temp[0])

    new_col_data.set_index(pd.to_datetime(new_index),inplace = True)
    cleaned_data = new_col_data.drop(('구분','구분'),axis=1)
    return cleaned_data

new_path = r'/Users/simjaegwang/Desktop/RAM/2019/Real_estate_python/kbdatas.xls'
new_data = '매매종합'
KBpriceindex_preprocessing(new_path,new_data)

                 전국       서울                                               \
                 전국       서울       강북      강북구      광진구      노원구      도봉구
1986-01-01  34.6561  30.0438    41.94     None     None     None     None
1986-02-01  34.6561  30.0438  41.8891     None     None     None     None
1986-03-01   34.708  30.0024  41.8891     None     None     None     None
1986-04-01  34.4486  29.8366  41.7366     None     None     None     None
1986-05-01  34.2929   29.588  41.2791     None     None     None     None
...             ...      ...      ...      ...      ...      ...      ...
2019-06-01  99.5385  100.037  100.254  100.865  99.8983  100.095  99.8762
2019-07-01  99.5314  100.302  100.521  101.004  100.212  100.442  100.074
2019-08-01  99.5861  100.682  101.017   102.99  100.668      101  100.224
2019-09-01  99.6396   101.06  101.292  103.051  100.877  101.222  100.438
2019-10-01  99.7334  101.432   101.53  103.091  101.267  101.366  100.562

                                       ...       경남                       \
               동대문구      마포구     서대문구  ...      의창구      진해구    양산    거제
1986-01-01     None     None     None  ...     None     None  None  None
1986-02-01     None     None     None  ...     None     None  None  None
1986-03-01     None     None     None  ...     None     None  None  None
1986-04-01     None     None     None  ...     None     None  None  None
1986-05-01     None     None     None  ...     None     None  None  None
...             ...      ...      ...  ...      ...      ...   ...   ...
2019-06-01  100.352  99.9908  101.142  ...  97.6907  99.0593  None  None
2019-07-01  100.723  100.317  101.636  ...   97.092  98.8455  None  None
2019-08-01  100.984  100.979  102.367  ...   96.993  98.8204  None  None
2019-09-01  101.329  101.442  102.674  ...  96.7089  98.2978  None  None
2019-10-01  101.627  101.881  102.845  ...  96.4059   98.046  None  None

                                     제주도      서귀포     기타지방
                 진주       김해    통영   제주도 제주/\n서귀포     기타지방
1986-01-01     None     None  None  None     None     None
1986-02-01     None     None  None  None     None     None
1986-03-01     None     None  None  None     None     None
1986-04-01     None     None  None  None     None     None
1986-05-01     None     None  None  None     None     None
...             ...      ...   ...   ...      ...      ...
2019-06-01  97.9095  96.9309  None  None  99.1183  98.5402
2019-07-01  97.4756   96.055  None  None  99.0396  98.2511
2019-08-01  98.4843  95.6924  None  None  99.0585  98.0999
2019-09-01  98.1888  95.3363  None  None  98.3358  97.9116
2019-10-01  97.9575  94.8948  None  None   97.879  97.7453

[406 rows x 186 columns]